server:
  port: 8888
    
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: c:/microservice-repo
#        git:
#          try-master-branch: false
#          default-label: main
#          uri: https://github.com/JulioZittei/alura-microservice-repo
#          search-paths: provider
         
